@host = http://localhost:3030

# @id = 

### Get all message
GET {{host}}/messages

### Get on message
# GET {{host}}/message/{{id}}

### Create new message
POST {{host}}/messages
Content-Type: application/json

[
    {
        "author": "", //Schema.Types.ObjectId
        "text": "" //String
    }
]