@host = http://localhost:3030

@id = 62d26d6958c551286fca4afb

### Get all users
GET {{host}}/users

### Get me info
GET {{host}}/me

### Get one user
GET {{host}}/users/{{id}}

### Create multiple users
POST {{host}}/users
Content-Type: application/json

[
    {
        "twitter_name": "", //String
        "first_name": "", //String
        "last_name": "", //String
        "email": "", //String
        "phone": "", //String
        "followers": "", //Numbers
        "image": "" //String
    }
]
